---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-dynamic-claim
spec:
  accessModes:
    - ReadWriteMany # can be accessed at a time by any no.of pods
  storageClassName: efs-dynamic-sc
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: efs-dynamic
  labels:
    purpose: efs-dynamic-demo
    project: roboshop
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: persistent-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: efs-dynamic-claim
---
apiVersion: v1
kind: Service
metadata:
  name: efs-dynamic-service
spec:
  type: LoadBalancer
  selector:
    purpose: efs-dynamic-demo
    project: roboshop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80