apiVersion: v1
kind: Pod
metadata:
  name: pod-demo
  labels:
    purpose: multi-container-demo
spec:
  containers:
    - name: nginx
      image:  nginx
    - name: almalinux
      image:  almalinux:9