apiVersion: v1
kind: Pod
metadata:
  name: env-config
  labels:
    project: roboshop
    env: dev
spec:
  containers:
    - name: nginx
      image: nginx
      envFrom:
      - configMapRef:
          name: pod-config
