apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
spec:
  type: NodePort
  selector:
    purpose: service-nodeport
    project: roboshop
    environment: dev
  ports:
    - port: 80
      targetPort: 80
      #nodePort: 30007 # if required u can specify nodeport within nodeport range. if u haven't specified any node port then kubernates assigns a port randomly
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-nodeport
  labels:
    purpose: service-nodeport
    project: roboshop
    environment: dev
spec:
  containers:
    - name: nginx # in 2 diff pods we can have same container name 
      image:  nginx