apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    purpose: rs-demo
    project: roboshop
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      purpose: rs-demo
      project: roboshop
      app: nginx
  template:
    metadata:
      labels:
        purpose: rs-demo
        project: roboshop
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
spec:
  type: LoadBalancer
  selector:
    purpose: rs-demo
    project: roboshop
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80      
